-- ============================================================================
-- Aartha — Migration 002: Vector Search & Hybrid Retrieval Infrastructure
-- ============================================================================
-- Enables pgvector extension, supplier embeddings table with HNSW index,
-- full-text lexical search index, match feedback signals, and evaluation storage.
-- ============================================================================

-- 1. Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Supplier Embeddings Table
-- Stores dense vector representations generated by text-embedding-3-small (512 dimensions)
CREATE TABLE IF NOT EXISTS supplier_embeddings (
    supplier_id TEXT PRIMARY KEY,
    embedding vector(512),
    embedding_text TEXT NOT NULL,
    embedding_model TEXT NOT NULL DEFAULT 'text-embedding-3-small',
    embedding_version INTEGER NOT NULL DEFAULT 1,
    dimensions INTEGER NOT NULL DEFAULT 512,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- HNSW Index for sub-10ms approximate nearest neighbor (ANN) cosine similarity
CREATE INDEX IF NOT EXISTS idx_supplier_embeddings_hnsw 
    ON supplier_embeddings USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- 3. Full-Text Search Vector Column on Suppliers
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS search_vector tsvector;

-- Function to automatically generate tsvector from supplier attributes
CREATE OR REPLACE FUNCTION generate_supplier_search_vector() RETURNS trigger AS $$
BEGIN
    NEW.search_vector := 
        setweight(to_tsvector('english', coalesce(NEW."companyName", '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.category, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(array_to_string(NEW.subcategories, ' '), '')), 'B') ||
        setweight(to_tsvector('english', coalesce(array_to_string(NEW.products, ' '), '')), 'B') ||
        setweight(to_tsvector('english', coalesce(array_to_string(NEW.certifications, ' '), '')), 'B') ||
        setweight(to_tsvector('english', coalesce(NEW.about, '')), 'C') ||
        setweight(to_tsvector('english', coalesce(NEW.location->>'city', '')), 'C') ||
        setweight(to_tsvector('english', coalesce(NEW.location->>'gidcZone', '')), 'C');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to keep search_vector synchronized on insert/update
DROP TRIGGER IF EXISTS trg_supplier_search_vector ON suppliers;
CREATE TRIGGER trg_supplier_search_vector
    BEFORE INSERT OR UPDATE ON suppliers
    FOR EACH ROW EXECUTE FUNCTION generate_supplier_search_vector();

-- GIN Index for rapid full-text lexical ranking
CREATE INDEX IF NOT EXISTS idx_suppliers_search_vector 
    ON suppliers USING gin(search_vector);

-- 4. Match Feedback Signal Table
-- Captures the complete interaction lifecycle: search -> view -> shortlist -> contact -> RFQ -> order -> rejection
CREATE TABLE IF NOT EXISTS match_feedback (
    id TEXT PRIMARY KEY,
    buyer_id TEXT,
    buyer_email TEXT,
    query_text TEXT,
    query_structured JSONB,
    supplier_id TEXT NOT NULL,
    signal_type TEXT NOT NULL CHECK (signal_type IN (
        'search_impression', 
        'view', 
        'shortlist', 
        'contact', 
        'rfq_sent', 
        'supplier_responded', 
        'quote_received', 
        'sample_requested', 
        'order_placed', 
        'repeat_order', 
        'rejection', 
        'no_response'
    )),
    rejection_reason TEXT,
    match_score NUMERIC,
    position_in_results INTEGER,
    session_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_match_feedback_supplier ON match_feedback(supplier_id);
CREATE INDEX IF NOT EXISTS idx_match_feedback_signal ON match_feedback(signal_type);
CREATE INDEX IF NOT EXISTS idx_match_feedback_buyer ON match_feedback(buyer_id);
CREATE INDEX IF NOT EXISTS idx_match_feedback_created ON match_feedback(created_at);

-- 5. Match Evaluation Benchmark Records
-- Persists benchmark runs against golden query-supplier relevance datasets
CREATE TABLE IF NOT EXISTS match_evaluations (
    id TEXT PRIMARY KEY,
    evaluation_set TEXT NOT NULL,
    total_queries INTEGER NOT NULL,
    system_version TEXT NOT NULL,
    system_type TEXT NOT NULL, -- 'baseline_deterministic' | 'hybrid_semantic'
    precision_at_5 NUMERIC NOT NULL,
    recall_at_5 NUMERIC NOT NULL,
    ndcg_at_5 NUMERIC NOT NULL,
    mrr NUMERIC NOT NULL,
    constraint_violation_rate NUMERIC NOT NULL,
    avg_latency_ms NUMERIC NOT NULL,
    cost_per_query_usd NUMERIC NOT NULL,
    query_results JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Row-Level Security Policies
ALTER TABLE supplier_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE match_feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE match_evaluations ENABLE ROW LEVEL SECURITY;

-- Public read for embeddings (used during search by client/server)
DROP POLICY IF EXISTS "Embeddings readable by backend and anon" ON supplier_embeddings;
CREATE POLICY "Embeddings readable by backend and anon" ON supplier_embeddings
    FOR SELECT USING (true);

-- Anyone can submit match interaction feedback
DROP POLICY IF EXISTS "Public can record match feedback" ON match_feedback;
CREATE POLICY "Public can record match feedback" ON match_feedback
    FOR INSERT WITH CHECK (true);

-- Read access restricted to service role
GRANT SELECT ON supplier_embeddings TO anon, authenticated;
GRANT INSERT ON match_feedback TO anon, authenticated;
GRANT ALL ON supplier_embeddings TO postgres, service_role;
GRANT ALL ON match_feedback TO postgres, service_role;
GRANT ALL ON match_evaluations TO postgres, service_role;
